### PR TITLE
Update start button to accommodate for issue 3

### PR DESCRIPTION
**Pull request by team-orangeBlue**
The button is downscaled to accommodate for the 2 checkboxes described in https://github.com/XiaomiSimulator/SimulatorAssets/issues/3

### CODE REVIEW

**Comment by mfn003** [comment]
why did you change the offset lmfao

**Comment by team-orangeBlue** [comment]
> why did you change the offset lmfao

the button is shifted down so you can place checkboxes at offset 50%

**Comment by UsrBinLuna** [comment]
mmmm yes pr war *grabs popcorn*

**Comment by team-orangeBlue** [comment]
image

**Comment by mfn003** [comment]
> > why did you change the offset lmfao
> 
> the button is shifted down so you can place checkboxes at offset 50%

omfg then that would be more to the top so that we could fit the options in the bottom ffs

**Comment by UsrBinLuna** [comment]
DSLR X20220704_062200689_8 4 400
i showed you my kernel 5.15.41 compilation with -j14 please respond

**Comment by team-orangeBlue** [comment]
> > > why did you change the offset lmfao
> > 
> > 
> > the button is shifted down so you can place checkboxes at offset 50%
> 
> omfg then that would be more to the top so that we could fit the options in the bottom ffs

who designed css in a way so the measuring goes from the damn bottom
roblox is simple, set scale+offset starting from top left and adding going to the right, simple

WHO IS SUCH A GENIUS
is it supposed to be offset at 40% then or what

**Comment by UsrBinLuna** [comment]
why are yall fighting
in
a
fucking
pr

**Comment by UsrBinLuna** [comment]
i almost clicked merge by accident

**Comment by mfn003** [comment]
> > > > why did you change the offset lmfao
> > > 
> > > 
> > > the button is shifted down so you can place checkboxes at offset 50%
> > 
> > 
> > omfg then that would be more to the top so that we could fit the options in the bottom ffs
> 
> who designed css in a way so the measuring goes from the damn bottom roblox is simple, set scale+offset starting from top left and adding going to the right, simple
> 
> WHO IS SUCH A GENIUS is it supposed to be offset at 40% then or what

YES ITS SUPPOSED TO BET AT 40
fix your branch and i'll merge

**Comment by team-orangeBlue** [comment]
> > > > > why did you change the offset lmfao
> > > > 
> > > > 
> > > > the button is shifted down so you can place checkboxes at offset 50%
> > > 
> > > 
> > > omfg then that would be more to the top so that we could fit the options in the bottom ffs
> > 
> > 
> > who designed css in a way so the measuring goes from the damn bottom roblox is simple, set scale+offset starting from top left and adding going to the right, simple
> > WHO IS SUCH A GENIUS is it supposed to be offset at 40% then or what
> 
> YES ITS SUPPOSED TO BET AT 40 fix your branch and i'll merge

fixed just merge it for god's sake

**Comment by mfn003** [comment]
actually can you make it 50 percent we'll change when we add the buttons :)

**Comment by team-orangeBlue** [comment]
> actually can you make it 50 percent we'll change when we add the buttons :)

sure one sec

**Comment by team-orangeBlue** [comment]
done

**Comment by mfn003** [comment]
i'm curious have you actually tested this

**Comment by team-orangeBlue** [comment]
> i'm curious have you actually tested this
no lol

**Comment by team-orangeBlue** [comment]
can you make the text smaller

**Comment by mfn003** [comment]
CAN YOU MAKE THE TEXT SMALLER

**Comment by UsrBinLuna** [comment]
this pr is amazing
also yes can **YOU** make the text smaller

**Comment by team-orangeBlue** [comment]
probably but im already working on a fork of your repo

**Comment by mfn003** [comment]
huwi simulation

**Comment by team-orangeBlue** [comment]
YES I MADE A NEW PR JUST MERGE IT I THINK IT FIXES IT

**Comment by UsrBinLuna** [comment]
I WILL LITERALLY HBREFDCMV IGHEFDV JDGORT8G9TRUGP9RSFURDF

**Comment by UsrBinLuna** [comment]
WHY DID I SIGN UP FOR EMAILS ON THIS THREAD

**Pull request merged**
