### PR TITLE
lockscreen: Make date/time text non-selectable

### PR DESCRIPTION
**Pull request by UsrBinLuna**
i literally have no write access as i said

### CODE REVIEW

**Comment by mfn003** [comment]
No need for `-moz-user-select: none;` and `-ms-user-select: none;`
- Firefox works with standard `user-select` rule
- We don't intend on supporting IE since `background-clip: text;` is not present which is required

**Comment by UsrBinLuna** [comment]
fixed it mf

**Comment by UsrBinLuna** [comment]
@TriDiscord

**Comment by UsrBinLuna** [comment]
fuck wait

**Comment by UsrBinLuna** [comment]
there

**Comment by mfn003** [comment]
i literally get mentioned for this stop fucking masspinging me

**Pull request merged**
